apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb-rag
type: Opaque
data:
  mongo-root-username: cG9zdF9tb25nb2RiX3VzZXI=
  mongo-root-password: cG9zdF9tb25nb2RiX3Bhc3M=
