spring.application.name=agregadorinvestimentos
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/agregador
spring.datasource.username=agregador_user
spring.datasource.password=agregador_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true